### ISSUE TITLE
The list

### ISSUE THREAD

**Issue by tendou0** [EchoLeague/Echo-League-Website-Testing#18]
Alright so I have multiple problems that I see within the first 2 minutes of registering.

1) MMR: I can understand that solo players need to show their MMR to play in this league maybe against solo players or what not, maybe even just something like quick games on faceit.   Here's what I don't understand, why do those of us that have a premade team need to show our MMR?  This should be fixed as a profile edit for solo players since teams should be playing against each other no matter the MMR range.  Or if you're gonna use the average MMR of the players, then maybe you use the "Team MMR" for premade teams for those that calibrated it, and for those that haven't, have them calibrate it.

2) MMR increase: "During the season, a player’s MMR must stay underneath xxxx MMR to remain a valid and eligible player
Players who exceed the above limit will not be allowed to play in official matches until their MMR drops below the limit. Prior games will all remain valid as long as the player in question’s MMR was below the limit at the time of the matches"
This was written in your rules.  Why is there a league that's requiring players to stop trying to climb?  Are we not allowed to climb MMR while we play the league with our team?

3) TEAMS:  The team creation isn't in any place obvious...  Is there even a team creation page?  Where we make the team and invite registered players into the team?

**Comment by ammuench** [comment]
1) Solo MMR will always be a requirement because we base team ranks off of a weighted system of their solo rankings.  

2) The rule as shown on the `/rules` page is very out of date.  Player during a season will be capped PER DIVISION based on signups.  So it will be variable for each division.  And the value we came up with was +500, which would require a roughly 70-80% winrate to get with normal play over the duration of group stages.  We don't want to prevent players from climbing, but if you're able to grind 500 MMR in such a short period you're clearly very well above where you were placed at registration, which is unfair to other players in your skill bracket

3. Team creation must be made via admin request.  The request is not clearly labelled anywhere yet, but will be soon

**Comment by tendou0** [comment]
Okay in that case

1. We need to get rid of the "requirement" of party mmr for registration and make that part optional.

2. This doesn't make sense to me. Are we basing divisions to every 500 mmr?  So 5k-5.5k, 5.5k-6k etc?  Then what happens to somebody that's sitting at 4975 MMR?

3. "Using all chat is forbidden, and will result in warning or forfeit (as decided by administration) except in these circumstances:
Explaining or discussing why a pause or issue has occurred
Wishing the other team, “Good luck, have fun” or of similar nature.
Calling/saying “gg” at the end or to end the game. Once “gg” is called, the game is instantly forfeited by the team who calls it, no exceptions will be made."

Going through the rules here I noticed this and thought you might also want to add how both teams must call "g" in all chat before unpausing

**Comment by ammuench** [comment]
1) Party is optional.  We just have it shown during registration to prevent someone with 2K solo registering with 5K party hidden

2) Talk to `@BaD` or `@Econ` in discord about it for a better explanation, but we're using a custom algorithm to generate EchoLeague Rank, which is a weighted MMR.  The driving idea is that MMR doesn't scale linearly, and that this will better group players of certain skillsets.  Some writeups have been done here:
https://blog.echoleague.gg/echo-league-skill-divisions-and-where-you-fit-in-them-a8c3f35ce10c#.px2s3ssn9
https://blog.echoleague.gg/true-sight-balancing-competitive-divisions-in-amateur-dota-leagues-9d53c7320e76#.wdtz6tji6

3. Can you move this issue here: https://github.com/EchoLeague/Echo-League-Rules/issues
This repo is specifically for website bugs, we're tracing rule stuff there 😄 

Thank you for the feedback

**Comment by tendou0** [comment]
Alright one last thing I'm noticing.  Discord servers vs profiles.  These need to be linked in case of scheduling issues that team captain/organizers need to talk to each other to agree to a reschedule before contacting an admin

**Comment by ammuench** [comment]
We are working on a system to do that eventually.  Right now we don't know if we'll have time to build it out before our registration date, so we've also [covered it in our rules:](https://github.com/EchoLeague/Echo-League-Rules/blob/master/RULES.md#ii-player-rules)
```
II.3.ii: 
All “Team Organizers” must be registered on the community Discord server, using their official “pro name” so other players can easily identify and contact them
```

**Comment by tendou0** [comment]
Alright, I got a new question as I dug a little deeper.  Not sure if this goes here or not... But my team consists of players from 3k flat solo to 5k solo... How is this gonna work?  Because the calculator.echoleague.gg is giving me

"Number of total points of team:
Err.
Team Division (A,B,C):
Err."
